#!/bin/env bash

source colors

# default editor
DEF_EDITOR="nvim"

FONT="Source Code Pro Medium:size=12"

# list of configs
CONFIG="$HOME/.config/bspwm/alacritty/alacritty.yml"
declare -a options=( 
"Alacritty - $HOME/.config/bspwm/alacritty/alacritty.yml"
"Alacritty (Fonts) - $HOME/.config/bspwm/alacritty/fonts.yml"
"BSPWM - $HOME/.config/bspwm/bspwmrc"
"SXHKD - $HOME/.config/sxhkd/sxhkdrc"
"Feh (Wallpaper Background) - $HOME/.config/bspwm/.fehbg"
"Fish - $HOME/.config/fish/config.fish"
"Picom - $HOME/.config/bspwm/picom.conf"
"Vim - $HOME/.vimrc"
)

# creates the menu
choice=$(printf '%s\n' "${options[@]}" | sort -u | dmenu -c -i -l 10 -nb "$bg" -nf "$fg" -sb "$altbg" -sf "$fg" -fn "$FONT" -p 'Edit Config:')

# opens the selected config file with vim
# exits otherwise
if [ "$choice" ]; then
    cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
    alacritty --config-file "$CONFIG" -e $DEF_EDITOR "$cfg"
else
    echo "Exiting..."; exit 1
fi
